### ISSUE TITLE
Step timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by Saisuryakattamuri** [Garethp/cucumber-nightwatch#1]
Hi Gareth

I've tried to execute your application, its launching the chrome but the URLs are not launched.
Could you help...

**Comment by Garethp** [comment]
Sorry, I no longer use or maintain this library. It was created when Nightwatch.JS didn't support Cucumber at all. You can probably find better libraries out there. From a quick, cursory search, it looks like you may want to try [this library](https://github.com/mucsi96/nightwatch-cucumber)
